# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/semiautowidget.ui'
#
# Created: Mon Jul 27 03:17:56 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SemiAutoWidget(object):
    def setupUi(self, SemiAutoWidget):
        SemiAutoWidget.setObjectName("SemiAutoWidget")
        SemiAutoWidget.resize(1021, 620)
        self.horizontalLayout = QtGui.QHBoxLayout(SemiAutoWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtGui.QGroupBox(SemiAutoWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButtonLoad = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_8.addWidget(self.pushButtonLoad)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButtonSave = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_9.addWidget(self.pushButtonSave)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.line = QtGui.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonContinue = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonContinue.setObjectName("pushButtonContinue")
        self.horizontalLayout_7.addWidget(self.pushButtonContinue)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonViewAll = QtGui.QPushButton(self.groupBox_6)
        self.pushButtonViewAll.setObjectName("pushButtonViewAll")
        self.horizontalLayout_2.addWidget(self.pushButtonViewAll)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalSlider = QtGui.QSlider(self.groupBox_6)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.widgetZinc = SemiAutoSceneviewerWidget(SemiAutoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetZinc.sizePolicy().hasHeightForWidth())
        self.widgetZinc.setSizePolicy(sizePolicy)
        self.widgetZinc.setObjectName("widgetZinc")
        self.horizontalLayout.addWidget(self.widgetZinc)

        self.retranslateUi(SemiAutoWidget)
        QtCore.QMetaObject.connectSlotsByName(SemiAutoWidget)

    def retranslateUi(self, SemiAutoWidget):
        SemiAutoWidget.setWindowTitle(QtGui.QApplication.translate("SemiAutoWidget", "Heart Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SemiAutoWidget", "Heart Surface Segmenter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("SemiAutoWidget", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoad.setText(QtGui.QApplication.translate("SemiAutoWidget", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("SemiAutoWidget", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonContinue.setText(QtGui.QApplication.translate("SemiAutoWidget", "Continue", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("SemiAutoWidget", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonViewAll.setText(QtGui.QApplication.translate("SemiAutoWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SemiAutoWidget", "Image Plane: ", None, QtGui.QApplication.UnicodeUTF8))

from mapclientplugins.heartsurfacesemiautosegmenterstep.view.semiautosceneviewerwidget import SemiAutoSceneviewerWidget
